import path from 'path';
import fs from 'fs';

const MIME_TYPES: Record<string, string> = {
  '.html': 'text/html',
  '.js': 'application/javascript',
  '.mjs': 'application/javascript',
  '.css': 'text/css',
  '.json': 'application/json',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.gif': 'image/gif',
  '.svg': 'image/svg+xml',
  '.ico': 'image/x-icon',
  '.woff': 'font/woff',
  '.woff2': 'font/woff2',
  '.ttf': 'font/ttf',
  '.eot': 'application/vnd.ms-fontobject',
  '.txt': 'text/plain',
};

export function serveStatic(webDir: string) {
  return async function(req: Request): Promise<Response | null> {
    const url = new URL(req.url);
    let pathname = url.pathname;
    
    // Skip API routes
    if (pathname.startsWith('/api/') || pathname.startsWith('/v1/')) {
      return null;
    }
    
    try {
      let filePath: string;
      
      if (pathname === '/') {
        filePath = path.join(webDir, 'index.html');
      } else {
        // Remove leading slash
        const relativePath = pathname.startsWith('/') ? pathname.slice(1) : pathname;
        filePath = path.join(webDir, relativePath);
      }
      
      // Security: ensure file is within webDir
      const resolvedPath = path.resolve(filePath);
      if (!resolvedPath.startsWith(path.resolve(webDir))) {
        return null;
      }
      
      // Check if file exists
      if (!fs.existsSync(filePath)) {
        // SPA fallback - serve index.html for non-asset requests
        const isAsset = path.extname(filePath) !== '';
        if (!isAsset) {
          filePath = path.join(webDir, 'index.html');
        } else {
          return null;
        }
      }
      
      if (!fs.existsSync(filePath)) {
        return null;
      }
      
      const stat = fs.statSync(filePath);
      if (!stat.isFile()) {
        return null;
      }
      
      const ext = path.extname(filePath).toLowerCase();
      const contentType = MIME_TYPES[ext] ?? 'application/octet-stream';

      // Serve precompressed .br/.gz siblings (generated by the client build's
      // precompress plugin) instead of compressing per request. Brotli wins
      // when offered; q=0 means "never send this coding".
      const accept = req.headers.get('accept-encoding') ?? '';
      const accepts = (coding: string) =>
        new RegExp(`(?:^|,\\s*)${coding}(?!\\s*;\\s*q=0)(?=,|;|$)`).test(accept);
      const headers: Record<string, string> = {
        'Content-Type': contentType,
        Vary: 'Accept-Encoding',
        // Hashed asset filenames never change content, so they can be cached
        // forever; index.html must always revalidate or a new deploy would be
        // masked by year-long browser caches.
        'Cache-Control': ext === '.html' ? 'no-cache' : 'public, max-age=31536000, immutable',
      };
      let bodyPath = filePath;
      if (accepts('br') && fs.existsSync(`${filePath}.br`)) {
        bodyPath = `${filePath}.br`;
        headers['Content-Encoding'] = 'br';
      } else if (accepts('gzip') && fs.existsSync(`${filePath}.gz`)) {
        bodyPath = `${filePath}.gz`;
        headers['Content-Encoding'] = 'gzip';
      }

      return new Response(Bun.file(bodyPath), { headers });
    } catch (err) {
      console.error('[Static] Error:', err);
      return null;
    }
  };
}
